# Generated by Django 5.1 on 2025-02-19 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controle', '0001_initial'),
        ('patrimonio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='bem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.bem', verbose_name='Bem'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='bem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.bem', verbose_name='Bem'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='departamento_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_destino', to='patrimonio.departamento', verbose_name='Departamento de Destino'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='departamento_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_origem', to='patrimonio.departamento', verbose_name='Departamento de Origem'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
