# Generated by Django 5.1 on 2025-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='gerente',
            field=models.BooleanField(default=False, verbose_name='Gerente'),
        ),
    ]
